server:
  port: 8080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    auto: true
  resources:
    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  datasource:
    url: jdbc:mysql://localhost:3306/framework?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.1.100
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 1

#mybatis
mybatis-plus:
  mapper-locations: classpath:com/framework/core/modules/*/mapper/xml/*Mapper.xml
  typeAliasesPackage: com.framework.core.modules.*.entity
  global-config:
    id-type: 0
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: false
    metaObjectHandler: com.framework.core.handler.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


logging:
  config: classpath:config/logback.xml

security:
  basic:
    enabled: false
liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-override.sql


sharedVariables:
  ossPath: assets/
  staticPath: /






